import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";

import "@mantine/core/styles.css";

import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  primaryColor: "original-gray",
  colors: {
    "original-gray": [
      "#fcfcfc",
      "#f9f9f9",
      "#f0f0f0",
      // "#e8e8e8",
      // "#e0e0e0",
      "#d9d9d9",
      "#cecece",
      "#bbbbbb",
      "#8d8d8d",
      "#838383",
      "#646464",
      "#202020",
    ],
  },
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <ColorSchemeScript />
        </head>
        <body className={inter.className}>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
