import { Metadata } from "next";

import { Box, Container } from "@mantine/core";

import AsideNav from "@/components/layout/aside-nav";
import FixedButton from "@/components/layout/d-fixed-button";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container
      size={"md"}
      display={"grid"}
      pos={"relative"}
      px={0}
      style={{ gridTemplateRows: "1fr auto" }}
    >
      <Box
        display={"grid"}
        mih={{ base: "100dvh", md: "90dvh" }}
        style={{
          gridTemplateColumns: "auto 1fr",
        }}
      >
        <AsideNav />
        <Box component="main" p={32} size={"sm"}>
          {children}
        </Box>
      </Box>
      <Footer />

      <FixedButton />
    </Container>
  );
}
