import { Metadata } from "next";

import { Box, Container } from "@mantine/core";

import AsideNav from "./aside-nav";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container
      size={"md"}
      display={"grid"}
      px={0}
      style={{ gridTemplateRows: "1fr auto" }}
    >
      {/* Fix height */}
      <Box
        display={"grid"}
        mih={"90dvh"}
        style={{
          gridTemplateColumns: "auto 1fr",
        }}
      >
        <AsideNav />
        <Box component="main" p={32} size={"sm"}>
          {children}
        </Box>
      </Box>
      <Footer />
    </Container>
  );
}
